AttributeError: "<pending_xref py:class=\"UnexpectedAttributeError\" py:module=\"\
  azure.ai.ml.exceptions\" refdoc=\"azure.ai.ml\" refdomain=\"py\" refexplicit=\"\
  False\" reftarget=\"AttributeError\" reftype=\"class\" refwarn=\"False\">\n    <literal\
  \ classes=\"xref py py-class\">\n        AttributeError\n"
object: "<pending_xref py:class=\"WorkspaceOperations\" py:module=\"azure.ai.ml.operations\"\
  \ refdoc=\"azure.ai.ml.operations\" refdomain=\"py\" refexplicit=\"False\" reftarget=\"\
  object\" reftype=\"class\" refwarn=\"False\">\n    <literal classes=\"xref py py-class\"\
  >\n        object\n"
str: "<pending_xref py:class=\"UsageUnit\" py:module=\"azure.ai.ml.entities\" refdoc=\"\
  azure.ai.ml.entities\" refdomain=\"py\" refexplicit=\"False\" reftarget=\"str\"\
  \ reftype=\"class\" refwarn=\"False\">\n    <literal classes=\"xref py py-class\"\
  >\n        str\n"
